version: '3.9'

services:
  db-redlock:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: redlock-web-2.0-db
    volumes:
      - ./src:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1
  
  php-redlock:
    build: .
    image: redlock-web-2.0
    ports:
      - "7077:80"
    volumes:
      - ./src/patch.php:/var/www/html
    depends_on:
      - db-redlock